name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: haskell:8.6

    services:
      eventstore:
        image: eventstore/eventstore:latest
        ports:
          - 1113:1113

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cabal --version
        cabal new-update
    - name: Build
      run: |
        cabal new-test
